"""
medlingo/pipeline/spr.py

Semantic Peer Review (SPR) — §III-C.

"MedLingo does not treat specialist outputs as final decisions. Instead,
the preliminary report and associated uncertainty score generated by Expert A
are injected into the context window of Expert B, and vice versa."

The SPR loop runs for up to `max_rounds` iterations. Early stopping occurs
when the delta between successive uncertainty scores drops below a threshold,
indicating the experts have converged.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

from medlingo.core.specialist import SpecialistExpert, ExpertFinding

logger = logging.getLogger(__name__)


@dataclass
class SPRTranscript:
    """Full record of the SPR dialogue between two experts."""
    expert_a_domain: str
    expert_b_domain: str
    rounds: List[dict] = field(default_factory=list)
    final_finding_a: Optional[ExpertFinding] = None
    final_finding_b: Optional[ExpertFinding] = None
    converged: bool = False
    rounds_completed: int = 0

    def to_text(self) -> str:
        """Serialize the SPR transcript for injection into the adjudicator context."""
        lines = [
            f"=== Semantic Peer Review: {self.expert_a_domain.upper()} ↔ {self.expert_b_domain.upper()} ===",
        ]
        for i, rnd in enumerate(self.rounds, 1):
            lines.append(f"\n--- Round {i} ---")
            lines.append(f"[{rnd['expert_a_domain'].upper()}] (U={rnd['uncertainty_a']:.3f}):")
            lines.append(rnd['report_a'])
            lines.append(f"\n[{rnd['expert_b_domain'].upper()}] (U={rnd['uncertainty_b']:.3f}):")
            lines.append(rnd['report_b'])

        if self.converged:
            lines.append("\n[SPR CONVERGED — experts reached consensus]")
        else:
            lines.append(f"\n[SPR COMPLETED — {self.rounds_completed} round(s)]")

        return "\n".join(lines)


class SemanticPeerReview:
    """
    Orchestrates the iterative cross-evaluation between two specialist experts.

    Parameters
    ----------
    max_rounds : int
        Maximum SPR iterations. Paper uses 2 rounds for 3.8s total latency.
    convergence_threshold : float
        Stop early if Δ uncertainty < this value across both experts.
    """

    def __init__(
        self,
        max_rounds: int = 2,
        convergence_threshold: float = 0.15,
    ) -> None:
        self._max_rounds = max_rounds
        self._threshold = convergence_threshold

    def run(
        self,
        expert_a: SpecialistExpert,
        expert_b: SpecialistExpert,
        finding_a: ExpertFinding,
        finding_b: ExpertFinding,
    ) -> SPRTranscript:
        """
        Execute the SPR loop between two initialized specialists.

        Parameters
        ----------
        expert_a, expert_b : SpecialistExpert
            The two activated specialists (already loaded with adapters).
        finding_a, finding_b : ExpertFinding
            Initial findings produced before SPR.

        Returns
        -------
        SPRTranscript
            Complete record with refined findings and convergence status.
        """
        transcript = SPRTranscript(
            expert_a_domain=expert_a.domain,
            expert_b_domain=expert_b.domain,
        )

        current_a = finding_a
        current_b = finding_b

        for round_idx in range(self._max_rounds):
            logger.info(
                "SPR Round %d/%d: %s ↔ %s",
                round_idx + 1, self._max_rounds,
                expert_a.domain, expert_b.domain,
            )

            prev_u_a = current_a.uncertainty_score
            prev_u_b = current_b.uncertainty_score

            # Expert A reads Expert B's report and refines
            refined_a = expert_a.refine_with_peer_feedback(current_a, current_b)

            # Expert B reads Expert A's (refined) report and refines
            refined_b = expert_b.refine_with_peer_feedback(current_b, refined_a)

            transcript.rounds.append({
                "expert_a_domain":  expert_a.domain,
                "expert_b_domain":  expert_b.domain,
                "report_a":         refined_a.report,
                "report_b":         refined_b.report,
                "uncertainty_a":    refined_a.uncertainty_score,
                "uncertainty_b":    refined_b.uncertainty_score,
            })

            delta_a = abs(refined_a.uncertainty_score - prev_u_a)
            delta_b = abs(refined_b.uncertainty_score - prev_u_b)

            current_a = refined_a
            current_b = refined_b

            logger.debug(
                "SPR Round %d — ΔU_a=%.4f, ΔU_b=%.4f (threshold=%.3f)",
                round_idx + 1, delta_a, delta_b, self._threshold,
            )

            if delta_a < self._threshold and delta_b < self._threshold:
                logger.info(
                    "SPR converged at round %d (ΔU below threshold).",
                    round_idx + 1,
                )
                transcript.converged = True
                break

        transcript.final_finding_a = current_a
        transcript.final_finding_b = current_b
        transcript.rounds_completed = len(transcript.rounds)

        return transcript
